---
- name: "Install eza on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: "eza-community.eza"

- name: "Deploy eza .config files"
  ansible.windows.win_copy:
    src: "{{ ansible_user_dir }}/.dotfiles/config/.config/eza"
    dest: "{{ ansible_user_dir }}/.config/eza"

- name: "Deploy eza powershell aliases files"
  ansible.windows.win_copy:
    src: "{{ ansible_user_dir }}/.dotfiles/config/.config/powershell/aliases/eza.ps1"
    dest: "{{ ansible_powershell_dir }}/aliases/eza.ps1"

- name: "Deploy eza powershell exports files"
  ansible.windows.win_copy:
    src: "{{ ansible_user_dir }}/.dotfiles/config/.config/powershell/exports/eza.ps1"
    dest: "{{ ansible_powershell_dir }}/exports/eza.ps1"
