---
- name: "Install eza on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: "eza-community.eza"

- name: "Ensure .config dir exists in ~/"
  ansible.windows.win_file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory

- name: "Ensure eza dir exists in ~/.config"
  ansible.windows.win_file:
    path: "{{ ansible_user_dir }}/.config/eza"
    state: directory

- name: "Deploy eza themes"
  ansible.windows.win_copy:
    src: theme.yml
    dest: "{{ ansible_user_dir }}/.config/eza/theme.yml"

- name: "Ensure profile dir exists in $PSHOME"
  ansible.builtin.win_powershell:
    script: New-Item "$PSHOME/profile" -ItemType Directory -ErrorAction SilentlyContinue

- name: "Ensure aliases dir exists in $PSHOME/profile"
  ansible.builtin.win_powershell:
    script: New-Item "$PSHOME/profile/aliases" -ItemType Directory -ErrorAction SilentlyContinue

- name: "Deploy eza aliases script"
  ansible.builtin.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [String]
        $file
      )

      Copy-Item $file -Destination "$PSHOME/profile/aliases/eza.ps1"
    parameters:
      file: "{{ role_path }}/files/aliases.ps1"

- name: "Ensure exports dir exists in $PSHOME/profile"
  ansible.builtin.win_powershell:
    script: New-Item "$PSHOME/profile/exports" -ItemType Directory -ErrorAction SilentlyContinue

- name: "Deploy eza exports script"
  ansible.builtin.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [String]
        $file
      )

      Copy-Item $file -Destination "$PSHOME/profile/exports/eza.ps1"
    parameters:
      file: "{{ role_path }}/files/exports.ps1"
