---
- name: "Install wezterm on MacOSX"
  community.general.homebrew_cask:
    name: wezterm
    state: present

- name: "Deploy wezterm .config files"
  ansible.builtin.copy:
    src: "{{ dotfiles }}/config/.config/wezterm"
    dest: "{{ ansible_user_dir }}/.config/wezterm"
