---
- name: "Install 1Password on MacOSX"
  community.general.homebrew_cask:
    name: "{{ app_item }}"
    state: present
  loop_control:
    loop_var: app_item
  loop:
    - 1password
    - 1password-cli

- name: "Deploy 1Password .config files"
  ansible.builtin.copy:
    src: "{{ dotfiles }}/config/.config/1password"
    dest: "{{ ansible_user_dir }}/.config/1password"
