---
- name: "Install 1Password on MacOSX"
  community.general.homebrew_cask:
    name: "{{ app_item }}"
    state: present
  loop_control:
    loop_var: app_item
  loop:
    - 1password
    - 1password-cli
