---
- name: "Ensure .config dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: "Ensure .config/1password dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/1Password"
    state: directory
    mode: "0755"

- name: "Ensure .config/1password/ssh dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/1Password/ssh"
    state: directory
    mode: "0755"

- name: "Deploy ssh config"
  ansible.builtin.copy:
    src: agent.toml
    dest: "{{ ansible_user_dir }}/.config/1Password/ssh/agent.toml"
    mode: "0644"
