---
- name: "Install 1Password on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: "{{ item }}"
  loop:
    - "AgileBits.1Password"
    - "AgileBits.1Password.CLI"

- name: "Deploy 1Password .config files"
  ansible.windows.win_copy:
    src: "{{ ansible_user_dir }}/.dotfiles/config/.config/1password"
    dest: "{{ ansible_user_dir }}/.config/1password"

- name: "Deploy ssh config"
  ansible.windows.win_copy:
    src: agent.toml
    dest: "{{ ansible_user_dir }}/.config/1Password/ssh/agent.toml"

- name: "Ensure 1Password dir exists in ~/AppData/Local"
  ansible.windows.win_file:
    path: "{{ lookup('ansible.builtin.env', 'LocalAppData') }}/1Password"
    state: directory

- name: "Ensure config dir exists in ~/AppData/Local/1Password"
  ansible.windows.win_file:
    path: "{{ lookup('ansible.builtin.env', 'LocalAppData') }}/1Password/config"
    state: directory

- name: "Ensure ssh dir exists in ~/AppData/Local/1password/config"
  ansible.windows.win_file:
    path: "{{ lookup('ansible.builtin.env', 'LocalAppData') }}/1Password/config/ssh"
    state: directory

- name: "Create symbolic link to configuration"
  ansible.builtin.win_powershell:
    script: |
      Remove-Item -Path $env:LOCALAPPDATA/1Password/config/ssh/agent.toml -Force -ErrorAction 'SilentlyContinue'
      New-Item -ItemType SymbolicLink -Path "$env:LOCALAPPDATA/1Password/config/ssh/agent.toml" -Target ".config/1password/ssh/agent.toml"
