---
- name: Detect current user when in Windows Subsystem for Linux
  ansible.windows.win_powershell:
    script: $env:UserName
  register: username
  changed_when: false
  failed_when: username.rc != 0
  when: ansible_host_environment == "windows"

- name: Register current user when in Windows Subsystem for Linux
  ansible.builtin.set_fact:
    ansible_host_user: "{{ username.stdout }}"
  when: ansible_host_environment == "windows"

- name: Register current user when not in Windows Subsystem for Linux
  ansible.builtin.set_fact:
    ansible_host_user: "{{ ansible_env['USER']}}"
  when: ansible_host_environment != "windows"

- name: DEBUG
  ansible.builtin.debug:
    msg: "ansible_host_user: {{ ansible_host_user }}"
