---
- name: Detect current user when in Windows Subsystem for Linux
  ansible.builtin.shell:
    cmd: $PSHOME
  register: powershell_directory
  changed_when: false
  failed_when: powershell_directory.rc != 0
  when: ansible_host_environment == "windows"
  args:
    executable: powershell.exe

- name: Register current user when in Windows Subsystem for Linux
  ansible.builtin.set_fact:
    ansible_powershell_dir: "{{ powershell_directory.stdout }}"
  when: ansible_host_environment == "windows"

- name: Register current user when in MacOSX
  ansible.builtin.set_fact:
    ansible_powershell_dir: "/usr/local/microsoft/powershell/7"
  when: ansible_host_environment != "windows"
