---
- name: "Install delta on MacOSX"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - less
    - git-delta

- name: "Deploy delta .config files"
  ansible.builtin.copy:
    src: "{{ dotfiles }}/config/.config/delta"
    dest: "{{ ansible_user_dir }}/.config/delta"
