---
- name: "Ensure config dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: "Ensure Starship config dir exists"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/starship"
    state: directory
    mode: "0755"

- name: "Deploy Starship config"
  ansible.builtin.copy:
    src: starship.toml
    dest: "{{ ansible_user_dir }}/.config/starship/starship.toml"
    mode: "0644"
