---
- name: "Install starship on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: "Starship.Starship"

- name: "Ensure profile dir exists in $PSHOME"
  ansible.builtin.win_powershell:
    script: New-Item "$PSHOME/profile" -ItemType Directory -ErrorAction SilentlyContinue

- name: "Ensure registration dir exists in $PSHOME/profile"
  ansible.builtin.win_powershell:
    script: New-Item "$PSHOME/profile/registration" -ItemType Directory -ErrorAction SilentlyContinue

- name: "Deploy powershell registration script"
  ansible.builtin.win_powershell:
    script: |
      [CmdletBinding()]
      param (
        [String]
        $file
      )

      Copy-Item $file -Destination "$PSHOME/profile/registration/starship.ps1"
    parameters:
      file: "{{ role_path }}/files/registration.ps1"
