devops:
  user:
    name: "op://Private/azure devops/name"
    email: "op://Private/azure devops/email"
  ssh:
    configs:
      - name: "id_devops"
        path: "op://Private/azure devops ssh"

os_include_roles:
  - powertoys

os_excluded_roles: []
