---
- name: "Install jq on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: jqlang.jq

- name: "Deploy jq powershell aliases files"
  ansible.windows.win_copy:
    src: "{{ dotfiles }}/config/.config/powershell/aliases/jq.ps1"
    dest: "{{ ansible_powershell_dir }}/aliases/jq.ps1"
