user: "weirdpattern"

git:
  user:
    name: "op://Private/github/name"
    email: "op://Private/github/email"
  ssh:
    signers: "op://Private/github/signers"
    configs:
      - name: "id_github"
        path: "op://Private/github ssh"

system:
  hosts: []

include_roles:
  - 1password
  - bat
  # - devops
  - eza
  # - ghostty
  - git
  - git-delta
  # - github
  # - neovim
  # - nu
  # - pwsh
  # - raycast
  # - ssh
  - starship
  # - system
  # - tana
  - tldr
  - vscode
  # - wezterm
  # - zsh

exclude_roles: []
