user: "weirdpattern"

dotfiles: "{{ ansible_user_dir }}/_/p/dotfiles"

git:
  user:
    name: "op://Private/github/name"
    email: "op://Private/github/email"
  ssh:
    signers: "op://Private/github/signers"
    configs:
      - name: "id_github"
        path: "op://Private/github ssh"

system:
  hosts: []

include_roles:
  - 1password
  - powershell
  - zsh
  - zig
  - starship
  - bat
  - ripgrep
  - fzf
  - eza
  - jq
  - git
  - delta
  - tldr
  - neovim
  - lazygit
  - vscode
  - wezterm
  # - devops
  # - github
  # - ssh
  # - system
  # - tana

exclude_roles: []
