---
- name: "Install git on MacOSX"
  community.general.homebrew_cask:
    name: git
    state: present

- name: "Ensure .config dir exists in ~/"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory
    mode: "0755"

- name: "Ensure git dir exists in ~/.config"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/git"
    state: directory
    mode: "0755"

- name: "Deploy git config"
  ansible.builtin.copy:
    src: config
    dest: "{{ ansible_user_dir }}/.config/git/config"
    mode: "0644"

- name: "Remove .gitconfig from ~/"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gitconfig"
    state: absent
