---
- name: "Install git on MacOSX"
  community.general.homebrew:
    name: git
    state: present

- name: "Deploy git .config files"
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/dotfiles/config/.config/git"
    dest: "{{ ansible_user_dir }}/.config/git"

- name: "Remove .gitconfig from {{ ansible_user_dir }}"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.gitconfig"
    state: absent
