---
- name: "Install git on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: "Git.Git"

- name: "Deploy git .config files"
  ansible.windows.win_copy:
    src: "{{ ansible_user_dir }}/.dotfiles/config/.config/git"
    dest: "{{ ansible_user_dir }}/.config/git"

- name: "Update ssh command"
  community.general.git_config:
    name: core.sshCommand
    scope: global
    value: "C:/Windows/System32/OpenSSH/ssh.exe"

- name: "Remove .gitconfig from {{ ansible_user_dir }}"
  ansible.builtin.win_file:
    path: "{{ ansible_user_dir }}/.gitconfig"
    state: absent
