return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    ensure_installed = {
      "bash",
      "c_sharp",
      "dockerfile",
      "editorconfig",
      "git_config",
      "gitattributes",
      "gitignore",
      "graphql",
      "html",
      "javascript",
      "jsdoc",
      "json",
      "kotlin",
      "lua",
      "make",
      "markdown",
      "markdown_inline",
      "nginx",
      "powershell",
      "regex",
      "rust",
      "sql",
      "ssh_config",
      "toml",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "xml",
      "yaml",
    },
  },
}
