---
- name: "Install tldr on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: "tldr-pages.tlrc"

- name: "Deploy tldr powershell aliases files"
  ansible.windows.win_copy:
    src: "{{ ansible_user_dir }}/.dotfiles/config/.config/powershell/aliases/tldr.ps1"
    dest: "{{ ansible_powershell_dir }}/aliases/tldr.ps1"
