---
- name: "Install ghostty on MacOSX"
  community.general.homebrew_cask:
    name: ghostty
    state: present

- name: "Deploy ghostty .config files"
  ansible.builtin.copy:
    src: "{{ dotfiles }}/config/.config/ghostty"
    dest: "{{ ansible_user_dir }}/.config/ghostty"
