---
- name: "Install git delta on MacOSX"
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - less
    - git-delta

- name: "Deploy git delta .config files"
  ansible.builtin.copy:
    src: "{{ ansible_user_dir }}/dotfiles/config/.config/git-delta"
    dest: "{{ ansible_user_dir }}/.config/git-delta"
