---
- name: "Install git delta on Windows"
  ansible.builtin.include_role:
    name: winget
  vars:
    winget_package: "{{ item }}"
  loop:
    - "jftuga.less"
    - "dandavison.delta"

- name: "Ensure .config dir exists in ~/"
  ansible.windows.win_file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory

- name: "Ensure delta dir exists in ~/.config"
  ansible.windows.win_file:
    path: "{{ ansible_user_dir }}/.config/delta"
    state: directory

- name: "Deploy delta themes"
  ansible.windows.win_copy:
    src: themes
    dest: "{{ ansible_user_dir }}/.config/delta/themes"
