---
- name: "Install git delta on Windows"
  chocolatey.chocolatey.win_chocolatey:
    name: "{{ item }}"
    state: present
  loop:
    - less
    - delta

- name: "Ensure .config dir exists in ~/"
  ansible.windows.win_file:
    path: "{{ ansible_user_dir }}/.config"
    state: directory

- name: "Ensure delta dir exists in ~/.config"
  ansible.windows.win_file:
    path: "{{ ansible_user_dir }}/.config/delta"
    state: directory

- name: "Deploy themes"
  ansible.windows.win_copy:
    src: themes
    dest: "{{ ansible_user_dir }}/.config/delta/themes"
